EmprestimoLivros/Controllers/EmprestimoController.cs
using ClosedXML.Excel;
using EmprestimoLivros.Data;
using EmprestimoLivros.Models;
using EmprestimoLivros.Services.EmprestimosService;
using EmprestimoLivros.Services.SessaoService;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Threading.Tasks;

namespace EmprestimoLivros.Controllers
{
    public class EmprestimoController : Controller
    {

        readonly private ISessaoInterface _sessaoInterface;
        readonly private IEmprestimosInterface _emprestimosInterface;

        public EmprestimoController(IEmprestimosInterface emprestimosInterface, ISessaoInterface sessaoInterface)
        {
            _sessaoInterface = sessaoInterface;
            _emprestimosInterface = emprestimosInterface;
        }

        public async Task<IActionResult> Index()
        {
            var usuario = _sessaoInterface.BuscarSessao();
            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            var emprestimos = await _emprestimosInterface.BuscarEmprestimos();

            return View(emprestimos.Dados);
        }

        [HttpGet]
        public IActionResult Cadastrar()
        {

            var usuario = _sessaoInterface.BuscarSessao();
            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }


            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Editar(int? id)
        {
            var usuario = _sessaoInterface.BuscarSessao();
            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            if (id == null || id == 0)
            {
                return NotFound();
            }

            var emprestimo = await _emprestimosInterface.BuscarEmprestimosPorId(id);

            return View(emprestimo.Dados);
        }

        [HttpGet]
        public async Task<IActionResult> Excluir(int? id)
        {

            var usuario = _sessaoInterface.BuscarSessao();
            if (usuario == null)
            {
                return RedirectToAction("Login", "Login");
            }

            var emprestimo = await _emprestimosInterface.BuscarEmprestimosPorId(id);

            return View(emprestimo.Dados);
        }

        public async Task<IActionResult> Exportar()
        {
            var dados = await _emprestimosInterface.BuscarDadosEmprestimoExcel();

            using (XLWorkbook workBook = new XLWorkbook())
            {
                workBook.AddWorksheet(dados, "Dados Empréstimo");

                using (MemoryStream ms = new MemoryStream())
                {
                    workBook.SaveAs(ms);
                    return File(ms.ToArray(), "application/vnd.openxmlformats-officedocument.spredsheetal.sheet", "Emprestimo.xls");
                }
            }
        }



        [HttpPost]
        public async Task<IActionResult> Cadastrar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {
                var emprestimoResult = await _emprestimosInterface.CadastrarEmprestimo(emprestimo);

                if (emprestimoResult.Status)
                {

                    TempData["MensagemSucesso"] = emprestimoResult.Mensagem;

                }
                else
                {
                    TempData["MensagemErro"] = emprestimoResult.Mensagem;
                    return View(emprestimo);

                }


                return RedirectToAction("Index");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Editar(EmprestimoModel emprestimo)
        {
            if (ModelState.IsValid)
            {

                var emprestimoResult = await _emprestimosInterface.EditarEmprestimo(emprestimo);

                if (emprestimoResult.Status)
                {

                    TempData["MensagemSucesso"] = emprestimoResult.Mensagem;
                }
                else
                {
                    TempData["MensagemErro"] = emprestimoResult.Mensagem;
                    return View(emprestimo);

                }

                return RedirectToAction("Index");
            }
            TempData["MensagemErro"] = "Algum erro ocorreu ao realizar a Edição!";
            return View(emprestimo);
        }

        [HttpPost]
        public async Task<IActionResult> Excluir(EmprestimoModel emprestimo)
        {
            if (emprestimo == null)
            {
                TempData["MensagemeErro"] = "Emprestimo não localizado";
                return View(emprestimo);

            }

            var emprestimoResult = await _emprestimosInterface.RemoveEmprestimo(emprestimo);

            if (emprestimoResult.Status)
            {

                TempData["MensagemSucesso"] = emprestimoResult.Mensagem;

            }
            else
            {
                TempData["MensagemeErro"] = emprestimoResult.Mensagem;
                return View(emprestimo);

            }





            return RedirectToAction("Index");

        }




    }


}

EmprestimoLivros/Views/Emprestimo/Cadastrar.cshtml
@model EmprestimoModel
@{
    ViewData["title"] = "Cadastrar Empréstimo";
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Cadastro de Empréstimos</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Cadastrar">

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control  text-light" asp-for="Fornecedor" id="Fornecedor1" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>

        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control  text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>

        </div>


        <div class="d-flex gap-5 mt-5">
        <button type="submit" class="btn btn-success w-50">Adicionar</button>
        <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Editar.cshtml
@model EmprestimoModel
@{
    ViewData["title"] = "Editar Empréstimo";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-light" role="alert">
        @TempData["MensagemErro"]
    </div>
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Edição de Empréstimos</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Editar">
        <input type="hidden" asp-for="Id"/>
        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?">
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor1" placeholder="Quem está emprestando o livro?">
            <span class="text-danger" asp-validation-for="Fornecedor"></span>

        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?">
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>

        </div>


        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-success w-50">Editar</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Excluir.cshtml
@model EmprestimoModel
@{
    ViewData["title"] = "Excluir Empréstimo";
}

@if (TempData["MensagemSucesso"] != null)
{
    <div class="alert alert-success text-light" role="alert">
        @TempData["MensagemSucesso"]
    </div>
}

@if (TempData["MensagemErro"] != null)
{
    <div class="alert alert-danger text-light" role="alert">
        @TempData["MensagemErro"]
    </div>
}

<div class="container bg-dark p-5 rounded-5">
    <div class="mb-5 text-center">
        <h1 class="text-light">Exclusão de registro</h1>
    </div>

    <form method="post" asp-asp-controller="Emprestimo" asp-action="Excluir">
        <input type="hidden" asp-for="Id" />

        <h2 class="text-light text-center fs-7">Tem certeza que deseja excluir o registro abaixo?</h2>

        <div class="mb-3">
            <label for="Recebedor" class="form-label text-light">Recebedor</label>
            <input type="text" class="form-control text-light" asp-for="Recebedor" id="Recebedor" placeholder="Quem está recebendo o livro?" disabled>
            <span class="text-danger" asp-validation-for="Recebedor"></span>
        </div>

        <div class="mb-3">
            <label for="Fornecedor" class="form-label text-light">Fornecedor:</label>
            <input type="text" class="form-control text-light" asp-for="Fornecedor" id="Fornecedor1" placeholder="Quem está emprestando o livro?" disabled>
            <span class="text-danger" asp-validation-for="Fornecedor"></span>

        </div>

        <div class="mb-3">
            <label for="Livro" class="form-label text-light">Livro</label>
            <input type="text" class="form-control text-light" asp-for="LivroEmprestado" id="Livro" placeholder="Qual é o livro que está sendo emprestado?" disabled>
            <span class="text-danger" asp-validation-for="LivroEmprestado"></span>

        </div>


        <div class="d-flex gap-5 mt-5">
            <button type="submit" class="btn btn-danger w-50">Excluir</button>
            <a class="btn btn-primary w-50" asp-controller="Emprestimo" asp-action="Index">Voltar</a>
        </div>
    </form>
</div>

EmprestimoLivros/Views/Emprestimo/Index.cshtml
@model IEnumerable<EmprestimoModel>
@{
    ViewData["title"] = "Emprestimos";
}

<div class="container ">

    <div class="d-flex justify-content-between align-items-center mb-5">
        <h1>Empréstimos</h1>

        <div>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Exportar"><i class="bi bi-file-earmark-plus mx-2"></i>Exportar</a>
            <a class="btn btn-success mx-2" asp-controller="Emprestimo" asp-action="Cadastrar"><i class="bi bi-file-earmark-plus mx-2"></i>Cadastrar novo empréstimo</a>
        </div>

    </div>
    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success text-light" role="alert">
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger text-light" role="alert">
            @TempData["MensagemErro"]
        </div>
    }


    <table id="Emprestimos" class="table table-light table-hover mt-5">
        <br />
        <thead>
            <tr>
                <th scope="col">Recebedor</th>
                <th scope="col">Fornecedor</th>
                <th scope="col">Livro</th>

                <th scope="col">Data empréstimo</th>

                <th></th>
            </tr>
        </thead>
        <tbody>

            @if (Model != null)
            {
                @foreach (var emprestimo in Model)
                {
                    <tr>
                        <th scope="row">@emprestimo.Recebedor</th>
                        <td>@emprestimo.Fornecedor</td>
                        <td>@emprestimo.LivroEmprestado</td>
                        <td>@emprestimo.DataEmprestimo</td>
                        <td>
                            <a class="btn btn-warning mx-2" asp-controller="Emprestimo" asp-action="Editar" asp-route-id="@emprestimo.Id"><i class="bi bi-pencil-square"></i>Editar</a>
                            <a class="btn btn-danger mx-2" asp-controller="Emprestimo" asp-action="Excluir" asp-route-id="@emprestimo.Id"><i class="bi bi-trash3-fill"></i>Excluir</a>
                        </td>
                    </tr>
                }
            }

        </tbody>
    </table>
</div>